<?php
/**
 *
 * phpBB Media Embed PlugIn extension for the phpBB Forum Software package.
 *
 * @copyright (c) 2026 phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * Implementation for scripts/update_mediaembed_sites.php.
 *
 */

const DEFAULT_BASE_VERSION = '2.11.5';
const DEFAULT_TARGET_VERSION = '2.19.3';

function update_mediaembed_sites()
{
	$options = getopt('', ['base:', 'target:', 'base-file:', 'target-file:', 'output:', 'check']);
	$output = isset($options['output']) ? $options['output'] : dirname(__DIR__) . '/collection/generated/upstream_sites.php';
	$base_version = isset($options['base']) ? $options['base'] : DEFAULT_BASE_VERSION;
	$target_version = isset($options['target']) ? $options['target'] : get_current_target_version($output);

	$base_source = isset($options['base-file']) ? read_source($options['base-file']) : download_collection($base_version);
	$target_source = isset($options['target-file']) ? read_source($options['target-file']) : download_collection($target_version);
	$base_sites = extract_sites($base_source);
	$target_sites = extract_sites($target_source);
	$changed_sites = [];

	foreach ($target_sites as $site_id => $definition)
	{
		if (!isset($base_sites[$site_id]) || $base_sites[$site_id] !== $definition)
		{
			$changed_sites[$site_id] = $definition;
		}
	}

	$removed_sites = array_values(array_diff(array_keys($base_sites), array_keys($target_sites)));
	sort($removed_sites, SORT_STRING);
	$generated = render_collection($base_version, $target_version, $changed_sites, $removed_sites);

	if (isset($options['check']))
	{
		$current = is_file($output) ? file_get_contents($output) : '';
		if ($current !== $generated)
		{
			fwrite(STDERR, "Generated MediaEmbed collection is out of date.\n");

			return 1;
		}

		echo "Generated MediaEmbed collection is current.\n";

		return 0;
	}

	$directory = dirname($output);
	if (!is_dir($directory) && !mkdir($directory, 0777, true) && !is_dir($directory))
	{
		throw new RuntimeException("Unable to create output directory '$directory'");
	}
	if (file_put_contents($output, $generated) === false)
	{
		throw new RuntimeException("Unable to write '$output'");
	}

	echo 'Generated ', count($changed_sites), ' changed/added definitions; ', count($removed_sites), " removed definitions.\n";

	return 0;
}

function download_collection($version)
{
	if (!preg_match('/^\d+\.\d+\.\d+$/D', $version))
	{
		throw new InvalidArgumentException("Invalid TextFormatter version '$version'");
	}

	$url = 'https://raw.githubusercontent.com/s9e/TextFormatter/' . $version
		. '/src/Plugins/MediaEmbed/Configurator/Collections/CachedDefinitionCollection.php';
	$context = stream_context_create([
		'http' => [
			'header' => "User-Agent: phpbb-mediaembed-definition-updater\r\n",
			'timeout' => 30,
		],
	]);
	$source = @file_get_contents($url, false, $context);
	if ($source === false)
	{
		throw new RuntimeException("Unable to download '$url'");
	}

	return $source;
}

function get_current_target_version($output)
{
	if (!is_file($output))
	{
		return DEFAULT_TARGET_VERSION;
	}

	$source = @file_get_contents($output);
	if ($source !== false && preg_match("/const TARGET_VERSION = '([0-9]+\\.[0-9]+\\.[0-9]+)';/", $source, $match))
	{
		return $match[1];
	}

	return DEFAULT_TARGET_VERSION;
}

function read_source($path)
{
	$source = @file_get_contents($path);
	if ($source === false)
	{
		throw new RuntimeException("Unable to read '$path'");
	}

	return $source;
}

function extract_sites($source)
{
	$sites = [];
	foreach (preg_split('/\R/', $source) as $line)
	{
		if (preg_match("/^\t\t'([a-z0-9]+)'=>(\[.*\]),?$/D", $line, $match))
		{
			$sites[$match[1]] = $match[2];
		}
	}

	if (!$sites)
	{
		throw new RuntimeException('No MediaEmbed site definitions found; upstream format may have changed');
	}

	return $sites;
}

function render_collection($base_version, $target_version, array $sites, array $removed_sites)
{
	$output = "<?php\n";
	$output .= "/**\n";
	$output .= " *\n";
	$output .= " * phpBB Media Embed PlugIn extension for the phpBB Forum Software package.\n";
	$output .= " *\n";
	$output .= " * @copyright (c) 2026 phpBB Limited <https://www.phpbb.com>\n";
	$output .= " * @license GNU General Public License, version 2 (GPL-2.0)\n";
	$output .= " *\n";
	$output .= " * Generated by scripts/update_mediaembed_sites.php. Do not edit manually.\n";
	$output .= " * Source: s9e/TextFormatter {$base_version}..{$target_version}\n";
	$output .= " * Copyright (c) the s9e authors; distributed under the MIT License.\n";
	$output .= " *\n";
	$output .= " */\n\n";
	$output .= "namespace phpbb\\mediaembed\\collection\\generated;\n\n";
	$output .= "class upstream_sites\n";
	$output .= "{\n";
	$output .= "\tconst BASE_VERSION = " . var_export($base_version, true) . ";\n";
	$output .= "\tconst TARGET_VERSION = " . var_export($target_version, true) . ";\n";
	$output .= "\tconst REMOVED_SITES = " . render_string_list($removed_sites) . ";\n";
	$output .= "\tconst SITES = [\n";
	foreach ($sites as $site_id => $definition)
	{
		$output .= "\t\t'{$site_id}' => {$definition},\n";
	}
	$output .= "\t];\n";
	$output .= "}\n";

	return $output;
}

function render_string_list(array $values)
{
	if (!$values)
	{
		return '[]';
	}

	$exported_values = array_map(function ($value) {
		return var_export($value, true);
	}, $values);

	return '[' . implode(', ', $exported_values) . ']';
}
